version : '3'
# Defining a personal Nextcloud server with Traefik and Portainer

services:
  traefik-proxy:
    # Handles TLS certs and http to https redirection
    image: traefik:2.8
    restart: always
    container_name: traefik
    command:
      # Enables the web UI
      - "--api.insecure=true"
      # Declares cooperation with docker
      - "--providers.docker"
      # Defines entry for regular http traffic.
      - "--entryPoints.web.address=:80"
      # Redirects http to https
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # Defines https entry
      - "--entryPoints.websecure.address=:443"
      

    ports:
      - "80:80"
      # For Web UI enabled by 'api-insecure'
      - "8080:8080"
    volumes:
      # Enables docker cooperation
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  nextcloud:
    image: nextcloud
    restart: always
    depends_on:
      - traefik-proxy
      - db-next
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      
    networks:
      - nextcloud_db_network
      
  db-next:
    image: mariadb
    restart: always
    command:
      - --transaction-isolation=READ-COMMITTED
      - --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    depends_on:
      - traefik-proxy
    networks:
      - nextcloud_db_network

networks:
  nextcloud_db_network:
    driver: bridge

volumes:
  nextcloud:
  db:
