version: "3"

volumes:
  nextcloud:
  nextcloud-db:

services:
  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    labels:
      - traefik.enable=false

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - nextcloud-db
    security_opt:
      - no-new-privileges:true
    networks:
        - nextcloud-db
        - proxy
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nextcloud-router.entrypoints=web"
      - "traefik.http.routers.nextcloud-router.rule=PathPrefix(`/`)"

      
networks:
  nextcloud-db:
    external: false
  proxy:
    external: true
