api:
#  insecure: true
  dashboard: true
  debug: true
entryPoints:
  traefik-dashboard:
    address: :8080
  portainer-entry:
    address: :8081
  web:
    address: :80
  #   http:
  #     redirections:
  #       entryPoint:
  #         to: websecure

  # websecure:
  #   address: :443
  #   http:
  #     middlewares:
  #       - secureHeaders@file
  #     tls:
  #       certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /configurations/dynamic.yml
    filename: /configurations/dynamic-password-hash.yml

# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: HERE SOME EMAIL PLS
#       storage: acme.json
#       keyType: EC384
#       httpChallenge:
#         entryPoint: web
