version: "3"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 8080:8080
#      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data/traefik.yml:/traefik.yml:ro
      - ./traefik-data/acme.json:/acme.json
      - ./traefik-data/configurations:/configurations
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # - "traefik.http.routers.traefik-secure.entrypoints=websecure"
      # - "traefik.http.routers.traefik-secure.rule=Host(`traefik.domain.com`)"
      # - "traefik.http.routers.traefik-secure.middlewares=user-auth@file"
      # - "traefik.http.routers.traefik-secure.service=api@internal"
      - "traefik.http.routers.traefik-unsecure.entrypoints=traefi"
      - "traefik.http.routers.traefik-unsecure.rule=PathPrefix(`/`)"
      - "traefik.http.routers.traefik-unsecure.middlewares=user-auth@file"
      - "traefik.http.routers.traefik-unsecure.service=api@internal"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # - "traefik.http.routers.portainer-secure.entrypoints=websecure"
      # - "traefik.http.routers.portainer-secure.rule=Host(`portainer.domain.com`)"
      # - "traefik.http.routers.portainer-secure.service=portainer"
      # - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer-unsecure.entrypoints=web"
#      - "traefik.http.routers.portainer-unsecure.rule=Host(`portainer.domain.com`)"
      - "traefik.http.routers.portainer-unsecure.rule=PathPrefix(`/`)"
      - "traefik.http.routers.portainer-unsecure.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  proxy:
    external: true
