api:
  # insecure: true
  dashboard: true
  debug: true
entryPoints:
  # traefik-dashboard:
  #   address: :8080
  # portainer-entry:
  #   address: :8081
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    # Commenting out dynami
    # filename: /configurations/dynamic.yml
    filename: /configurations/dynamic-password-hash.yml

certificatesResolvers:
  letsencrypt:
    acme:
      # Comment out non-staging caServer when sure it works.
      caServer: https://acme-v02.api.letsencrypt.org/directory
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: zwin1vnwy8xc@opayq.com
      storage: acme.json
      keyType: EC384
      httpChallenge:
        entryPoint: web
